#!/bin/bash
# Configure Codex CLI for Burp MCP integration

set -e

CONFIG_FILE="${HOME}/.codex/config.toml"
PROXY_JAR="${1:-$HOME/burp-mcp/mcp-proxy.jar}"

echo "🔧 Configuring Codex CLI for Burp MCP..."

# Check if proxy JAR exists
if [[ ! -f "$PROXY_JAR" ]]; then
    echo "❌ Proxy JAR not found at: $PROXY_JAR"
    echo ""
    echo "💡 To extract the proxy JAR:"
    echo "   1. Open Burp Suite → Extensions → MCP Server"
    echo "   2. Click 'Extract server proxy jar'"
    echo "   3. Save mcp-proxy.jar to: $PROXY_JAR"
    echo ""
    echo "Or run this script with the correct path:"
    echo "   $0 /path/to/mcp-proxy.jar"
    exit 1
fi

# Create config directory if needed
mkdir -p "$(dirname "$CONFIG_FILE")"

# Backup existing config
if [[ -f "$CONFIG_FILE" ]]; then
    cp "$CONFIG_FILE" "${CONFIG_FILE}.backup.$(date +%Y%m%d%H%M%S)"
    echo "📦 Backed up existing config"
fi

# Generate config
cat > "$CONFIG_FILE" <<EOF
# Burp MCP configuration
# Generated by configure-codex.sh

[mcp_servers.burp]
command = "java"
args = ["-jar", "$PROXY_JAR", "--sse-url", "http://127.0.0.1:19876"]
EOF

echo "✅ Codex config created at: $CONFIG_FILE"
echo ""
echo "📋 Next steps:"
echo "   1. Ensure Caddy proxy is running (if using port 19876)"
echo "      caddy run --config ~/burp-mcp/Caddyfile &"
echo "   2. Start Codex: codex"
echo "   3. Verify MCP tools: /mcp"
echo ""
echo "💡 If you get handshake errors, run:"
echo "   ./scripts/setup-caddy-proxy.sh"
