#!/bin/bash
# macOS Sandbox Profile Generator
# Usage: ./create-sandbox-profile.sh [options]

set -e

PROFILE_NAME="custom"
OUTPUT_FILE="/tmp/${PROFILE_NAME}.sb"
DEFAULT_DENY=true
ALLOW_NETWORK=false
ALLOW_FILE_READ=false
ALLOW_FILE_WRITE=false
FILE_PATHS=""
PROCESS_PATHS=""

usage() {
    cat << EOF
Usage: $0 [options]

Generate a macOS Sandbox profile (SBPL format)

Options:
  -n, --name NAME        Profile name (default: custom)
  -o, --output FILE      Output file path (default: /tmp/NAME.sb)
  -d, --default-allow    Use (allow default) instead of (deny default)
  -N, --network          Allow network access
  -r, --read PATHS       Allow file read from paths (comma-separated)
  -w, --write PATHS      Allow file write to paths (comma-separated)
  -p, --process PATHS    Allow process execution (comma-separated)
  -h, --help             Show this help

Examples:
  $0 -n test -r "/tmp,/Users/me/Downloads" -p "/usr/bin/python3"
  $0 --network --read "/var/www" --output /tmp/webserver.sb
EOF
    exit 0
}

while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--name)
            PROFILE_NAME="$2"
            OUTPUT_FILE="/tmp/${PROFILE_NAME}.sb"
            shift 2
            ;;
        -o|--output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        -d|--default-allow)
            DEFAULT_DENY=false
            shift
            ;;
        -N|--network)
            ALLOW_NETWORK=true
            shift
            ;;
        -r|--read)
            FILE_PATHS="$2"
            ALLOW_FILE_READ=true
            shift 2
            ;;
        -w|--write)
            FILE_PATHS="$2"
            ALLOW_FILE_WRITE=true
            shift 2
            ;;
        -p|--process)
            PROCESS_PATHS="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

# Generate profile
cat > "$OUTPUT_FILE" << 'HEADER'
; macOS Sandbox Profile
; Generated by create-sandbox-profile.sh
; Edit this file as needed

(version 1)
HEADER

if [ "$DEFAULT_DENY" = true ]; then
    echo "(deny default)" >> "$OUTPUT_FILE"
else
    echo "(allow default)" >> "$OUTPUT_FILE"
fi

# Network
if [ "$ALLOW_NETWORK" = true ]; then
    echo "" >> "$OUTPUT_FILE"
    echo "; Network access" >> "$OUTPUT_FILE"
    echo "(allow network*)" >> "$OUTPUT_FILE"
fi

# File read
if [ "$ALLOW_FILE_READ" = true ] && [ -n "$FILE_PATHS" ]; then
    echo "" >> "$OUTPUT_FILE"
    echo "; File read access" >> "$OUTPUT_FILE"
    echo "(allow file-read*" >> "$OUTPUT_FILE"
    IFS=',' read -ra PATHS <<< "$FILE_PATHS"
    for path in "${PATHS[@]}"; do
        echo "    (literal \"$path\")" >> "$OUTPUT_FILE"
    done
    echo ")" >> "$OUTPUT_FILE"
fi

# File write
if [ "$ALLOW_FILE_WRITE" = true ] && [ -n "$FILE_PATHS" ]; then
    echo "" >> "$OUTPUT_FILE"
    echo "; File write access" >> "$OUTPUT_FILE"
    echo "(allow file-write*" >> "$OUTPUT_FILE"
    IFS=',' read -ra PATHS <<< "$FILE_PATHS"
    for path in "${PATHS[@]}"; do
        echo "    (literal \"$path\")" >> "$OUTPUT_FILE"
    done
    echo ")" >> "$OUTPUT_FILE"
fi

# Process execution
if [ -n "$PROCESS_PATHS" ]; then
    echo "" >> "$OUTPUT_FILE"
    echo "; Process execution" >> "$OUTPUT_FILE"
    echo "(allow process*" >> "$OUTPUT_FILE"
    IFS=',' read -ra PATHS <<< "$PROCESS_PATHS"
    for path in "${PATHS[@]}"; do
        echo "    (literal \"$path\")" >> "$OUTPUT_FILE"
    done
    echo ")" >> "$OUTPUT_FILE"
fi

echo ""
echo "Profile created: $OUTPUT_FILE"
echo ""
echo "To test:"
echo "  sandbox-exec -f $OUTPUT_FILE /path/to/command"
echo ""
echo "To trace sandbox checks:"
echo "  sandbox-exec -t /tmp/trace.out -f $OUTPUT_FILE /path/to/command"
