#!/bin/bash
# List all macOS TCC service types
# macOS security testing utility

echo "=== macOS TCC Service Types ==="
echo ""
echo "File System Access:"
echo "  - kTCCServiceSystemPolicyDesktopFolder"
echo "  - kTCCServiceSystemPolicyDocumentsFolder"
echo "  - kTCCServiceSystemPolicyDownloadsFolder"
echo ""
echo "Personal Information:"
echo "  - kTCCServicePhotos (com.apple.security.personal-information.photos-library)"
echo "  - kTCCServiceAddressBook (com.apple.security.personal-information.addressbook)"
echo "  - kTCCServiceCalendar (com.apple.security.personal-information.calendars)"
echo "  - kTCCServiceLocation (com.apple.security.personal-information.location)"
echo ""
echo "Hardware Access:"
echo "  - kTCCServiceCamera (com.apple.security.device.camera)"
echo "  - kTCCServiceMicrophone (com.apple.security.device.audio-input)"
echo ""
echo "System Access:"
echo "  - kTCCServiceScreenCapture"
echo "  - kTCCServiceAccessibility"
echo ""
echo "=== TCC Database Location ==="
echo "  /Library/Application Support/com.apple.TCC/TCC.db"
echo ""
echo "=== Location Services Database ==="
echo "  /var/db/locationd/clients.plist"
