#!/bin/bash
# LLDB debugging workflow for macOS sandbox
# Usage: ./lldb_sandbox_debug.sh <binary_path>

BINARY="${1:-./sand}"

if [ ! -f "$BINARY" ]; then
    echo "Error: Binary '$BINARY' not found"
    echo "Usage: ./lldb_sandbox_debug.sh <binary_path>"
    exit 1
fi

echo "=== LLDB Sandbox Debugging Workflow ==="
echo "Binary: $BINARY"
echo ""
echo "This script provides the LLDB commands for sandbox debugging."
echo "Run these commands in lldb:"
echo ""
echo "1. Start lldb:"
echo "   lldb $BINARY"
echo ""
echo "2. Set breakpoint on sandbox initialization:"
echo "   (lldb) b xpc_pipe_routine"
echo ""
echo "3. Run the program:"
echo "   (lldb) r"
echo ""
echo "4. Check backtrace (look for libsecinit):"
echo "   (lldb) bt"
echo "   # Should show: libsystem_secinit.dylib\`_libsecinit_appsandbox"
echo ""
echo "5. Increase string display limit:"
echo "   (lldb) settings set target.max-string-summary-length 10000"
echo ""
echo "6. View XPC message (2nd arg of xpc_pipe_routine):"
echo "   (lldb) p (char *) xpc_copy_description(\$x1)"
echo ""
echo "7. View response address (3rd arg):"
echo "   (lldb) register read x2"
echo ""
echo "8. Continue to end of function:"
echo "   (lldb) finish"
echo ""
echo "9. Read sandbox response:"
echo "   (lldb) memory read -f p <x2_value> -c 1"
echo "   (lldb) p (char *) xpc_copy_description(<result>)"
echo ""
echo "10. Set conditional breakpoint on __mac_syscall:"
echo "    (lldb) breakpoint set --name __mac_syscall --condition '(\$x1 == 0)'"
echo "    (lldb) c"
echo ""
echo "11. View policy name:"
echo "    (lldb) memory read -f s \$x0"
echo ""
echo "12. BYPASS - Skip sandbox activation:"
echo "    (lldb) breakpoint delete 1"
echo "    (lldb) register write \$pc 0x187659928  # b.lo address (may vary)"
echo "    (lldb) register write \$x0 0x00"
echo "    (lldb) register write \$x1 0x00"
echo "    (lldb) register write \$x16 0x17d"
echo "    (lldb) c"
echo ""
echo "Note: The b.lo address (0x187659928) may vary by macOS version."
echo "      Find it by examining the disassembly at the breakpoint."
echo ""
echo "Starting lldb now..."
lldb "$BINARY"
