#!/usr/bin/env python3
"""
Generate detection rules for Ashen Lepus DLL side-loading technique.
Outputs Sigma rules, YARA rules, and network detection patterns.

Usage:
    python generate_detection_rules.py
    python generate_detection_rules.py --format sigma
    python generate_detection_rules.py --output detections/
"""

import argparse
import json
from pathlib import Path
from datetime import datetime


SIGMA_RULES = {
    'dll_sideload_detection': {
        'title': 'Ashen Lepus DLL Side-Loading Detection',
        'status': 'experimental',
        'description': 'Detects suspicious DLL loading patterns associated with Ashen Lepus/WIRTE',
        'author': 'Generated by Ashen Lepus Analysis Skill',
        'date': datetime.now().strftime('%Y-%m-%d'),
        'references': [
            'https://unit42.paloaltonetworks.com/hamas-affiliate-ashen-lepus-uses-new-malware-suite-ashtag/'
        ],
        'tags': ['attack.execution', 'attack.t1574.001'],
        'logsource': {
            'category': 'process_creation',
            'product': 'windows'
        },
        'detection': {
            'selection': [
                'Image|endswith: \'\\\\netutils.dll\'',
                'Image|endswith: \'\\\\srvcli.dll\'',
                'Image|endswith: \'\\\\dwampi.dll\'',
                'Image|endswith: \'\\\\wtsapi32.dll\'',
                'Image|endswith: \'\\\\propsys.dll\''
            ],
            'filter': [
                'Image|contains: \'\\\\Windows\\\\System32\'',
                'Image|contains: \'\\\\Windows\\\\SysWOW64\''
            ],
            'condition': 'selection and not filter'
        },
        'falsepositives': ['Legitimate software using similar DLL names'],
        'level': 'high'
    },
    'scheduled_task_persistence': {
        'title': 'Ashen Lepus Scheduled Task Persistence',
        'status': 'experimental',
        'description': 'Detects scheduled tasks matching Ashen Lepus persistence patterns',
        'author': 'Generated by Ashen Lepus Analysis Skill',
        'date': datetime.now().strftime('%Y-%m-%d'),
        'references': [
            'https://unit42.paloaltonetworks.com/hamas-affiliate-ashen-lepus-uses-new-malware-suite-ashtag/'
        ],
        'tags': ['attack.persistence', 'attack.t1053.005'],
        'logsource': {
            'category': 'process_creation',
            'product': 'windows'
        },
        'detection': {
            'selection': [
                'CommandLine|contains: \'WindowsDefenderUpdate\'',
                'CommandLine|contains: \'WindowsServicesUpdate\'',
                'CommandLine|contains: \'Automatic Windows Update\''
            ],
            'filter': [
                'CommandLine|contains: \'\\\\Windows\\\\System32\\\\\''
            ],
            'condition': 'selection and not filter'
        },
        'falsepositives': ['Legitimate Windows update tasks'],
        'level': 'medium'
    },
    'rclone_exfiltration': {
        'title': 'Suspicious Rclone Execution',
        'status': 'experimental',
        'description': 'Detects Rclone execution from non-standard locations',
        'author': 'Generated by Ashen Lepus Analysis Skill',
        'date': datetime.now().strftime('%Y-%m-%d'),
        'tags': ['attack.exfiltration', 'attack.t1567'],
        'logsource': {
            'category': 'process_creation',
            'product': 'windows'
        },
        'detection': {
            'selection': {
                'Image|contains': 'rclone'
            },
            'filter': [
                'Image|contains: \'\\\\Program Files\\\\\'',
                'Image|contains: \'\\\\Program Files (x86)\\\\\''
            ],
            'condition': 'selection and not filter'
        },
        'falsepositives': ['Legitimate Rclone usage in non-standard paths'],
        'level': 'medium'
    }
}


YARA_RULES = '''
rule AshenLepus_HTML_Staging {
    meta:
        description = "Detects HTML-staged C2 payloads with dynamic tag extraction"
        author = "Generated by Ashen Lepus Analysis Skill"
        reference = "https://unit42.paloaltonetworks.com/hamas-affiliate-ashen-lepus-uses-new-malware-suite-ashtag/"
        tags = "c2, html_smuggling, wirte"
    strings:
        $tag_comment = "<!-- TAG:" ascii
        $headerp = "<headerp>" ascii
        $article_tag = "<article>" ascii
        $dll_names = (
            "netutils.dll"
            "srvcli.dll"
            "dwampi.dll"
            "wtsapi32.dll"
            "propsys.dll"
        ) ascii
        $api_path = "/api/v[12]/account" ascii
        $xor_key = "msasn1.dll" ascii
    condition:
        any of them
}

rule AshenLepus_ScheduledTask {
    meta:
        description = "Detects Ashen Lepus persistence scheduled tasks"
        author = "Generated by Ashen Lepus Analysis Skill"
        tags = "persistence, scheduled_task, wirte"
    strings:
        $task1 = "WindowsDefenderUpdate\\Windows Defender Updater" ascii
        $task2 = "WindowsServicesUpdate\\Windows Services Updater" ascii
        $task3 = "Automatic Windows Update" ascii
    condition:
        any of them
}

rule AshenLepus_DLL_Sideloader {
    meta:
        description = "Detects DLL side-loading loader patterns"
        author = "Generated by Ashen Lepus Analysis Skill"
        tags = "dll_sideload, loader, wirte"
    strings:
        $dll_imports = (
            "LoadLibraryA"
            "LoadLibraryW"
            "GetProcAddress"
        ) wide
        $dll_names = (
            "netutils.dll"
            "srvcli.dll"
            "dwampi.dll"
            "wtsapi32.dll"
            "propsys.dll"
        ) ascii
        $aes_pattern = "AES-CTR" ascii
    condition:
        uint16(0) == 0x5A4D and // MZ header
        all of ($dll_imports) and
        any of ($dll_names)
}
'''


NETWORK_DETECTION = {
    'suricata_rules': [
        {
            'name': 'ASHEN-LEPUS-HTML-STAGING',
            'rule': 'alert http any any -> any any (msg:"Ashen Lepus HTML Staging - TAG comment detected"; content:"<!-- TAG:"; nocase; content:"-->"; distance:0; within:50; sid:1000001; rev:1;)',
            'description': 'Detects HTML comment pattern used for dynamic tag extraction'
        },
        {
            'name': 'ASHEN-LEPUS-C2-PATH',
            'rule': 'alert http any any -> any any (msg:"Ashen Lepus C2 API path detected"; content:"/api/v"; nocase; content:"/account"; distance:0; within:20; sid:1000002; rev:1;)',
            'description': 'Detects C2 API path patterns'
        },
        {
            'name': 'ASHEN-LEPUS-BASE64-BLOB',
            'rule': 'alert http any any -> any any (msg:"Potential Ashen Lepus Base64 payload in HTML"; content:"<headerp>"; nocase; content:"</headerp>"; nocase; distance:0; within:10000; sid:1000003; rev:1;)',
            'description': 'Detects Base64 payloads in headerp tags'
        }
    ],
    'query_parameters': [
        'token=',
        'id=',
        'q=',
        'auth='
    ],
    'suspicious_user_agents': [
        'Exact User-Agent matching required for payload delivery'
    ]
}


def generate_sigma_rules(output_dir: Path) -> None:
    """Generate Sigma rule files."""
    sigma_dir = output_dir / 'sigma'
    sigma_dir.mkdir(parents=True, exist_ok=True)
    
    for rule_name, rule_data in SIGMA_RULES.items():
        rule_file = sigma_dir / f'{rule_name}.yml'
        with open(rule_file, 'w') as f:
            json.dump(rule_data, f, indent=2)
        print(f"[+] Created Sigma rule: {rule_file}")


def generate_yara_rules(output_dir: Path) -> None:
    """Generate YARA rule files."""
    yara_dir = output_dir / 'yara'
    yara_dir.mkdir(parents=True, exist_ok=True)
    
    rule_file = yara_dir / 'ashen_lepus_detection.yar'
    with open(rule_file, 'w') as f:
        f.write(YARA_RULES)
    print(f"[+] Created YARA rules: {rule_file}")


def generate_network_rules(output_dir: Path) -> None:
    """Generate network detection rules."""
    network_dir = output_dir / 'network'
    network_dir.mkdir(parents=True, exist_ok=True)
    
    # Suricata rules
    suricata_file = network_dir / 'ashen_lepus.rules'
    with open(suricata_file, 'w') as f:
        f.write("# Ashen Lepus Network Detection Rules\n")
        f.write(f"# Generated: {datetime.now().isoformat()}\n\n")
        for rule in NETWORK_DETECTION['suricata_rules']:
            f.write(f"# {rule['description']}\n")
            f.write(f"{rule['rule']}\n\n")
    print(f"[+] Created Suricata rules: {suricata_file}")
    
    # Detection summary
    summary_file = network_dir / 'detection_summary.json'
    with open(summary_file, 'w') as f:
        json.dump(NETWORK_DETECTION, f, indent=2)
    print(f"[+] Created detection summary: {summary_file}")


def generate_all(output_dir: Path) -> None:
    """Generate all detection rules."""
    print(f"\nGenerating detection rules for: {output_dir}")
    print("=" * 60)
    
    generate_sigma_rules(output_dir)
    generate_yara_rules(output_dir)
    generate_network_rules(output_dir)
    
    print("\n" + "=" * 60)
    print("Detection rule generation complete!")
    print(f"\nOutput directory: {output_dir}")
    print("\nGenerated files:")
    print(f"  - {output_dir}/sigma/ - Sigma rules for SIEM")
    print(f"  - {output_dir}/yara/ - YARA rules for file scanning")
    print(f"  - {output_dir}/network/ - Network detection rules")


def main():
    parser = argparse.ArgumentParser(
        description='Generate detection rules for Ashen Lepus technique'
    )
    parser.add_argument(
        '--output', '-o',
        default='detections',
        help='Output directory for rules (default: detections)'
    )
    parser.add_argument(
        '--format', '-f',
        choices=['all', 'sigma', 'yara', 'network'],
        default='all',
        help='Rule format to generate (default: all)'
    )
    
    args = parser.parse_args()
    output_dir = Path(args.output)
    
    if args.format == 'all':
        generate_all(output_dir)
    elif args.format == 'sigma':
        generate_sigma_rules(output_dir)
    elif args.format == 'yara':
        generate_yara_rules(output_dir)
    elif args.format == 'network':
        generate_network_rules(output_dir)


if __name__ == '__main__':
    main()
