#!/bin/bash
# macOS Firewall Audit: Inspect PF Rules
# Displays Packet Filter rules generated by GUI firewalls

set -e

echo "=== macOS PF Rules Audit ==="
echo "Timestamp: $(date)"
echo ""

echo "Checking for PF rules..."
if ! sudo pfctl -sr 2>/dev/null | grep -q .; then
    echo "No PF rules found or PF is not enabled."
    echo "Note: Some firewalls use Network Extension framework instead of PF."
    exit 0
fi

echo ""
echo "All PF rules:"
sudo pfctl -sr

echo ""
echo "Application Firewall rules (com.apple/250.ApplicationFirewall):"
sudo pfctl -a com.apple/250.ApplicationFirewall -sr 2>/dev/null || echo "No Application Firewall rules found"

echo ""
echo "Checking for 'quick' keyword rules (potential Sonoma bug):"
if sudo pfctl -sr 2>/dev/null | grep -q "quick"; then
    echo "WARNING: Found 'quick' rules - verify macOS build >= 23A344"
    sudo pfctl -sr | grep quick
else
    echo "No 'quick' rules found."
fi

echo ""
echo "Current macOS version:"
sw_vers
