#!/bin/bash
# I2C Bus Pirate Command Reference
# Quick reference for common I2C operations

echo "=== I2C Bus Pirate Command Reference ==="
echo ""
echo "Basic Commands:"
echo "  ~           - Run self-test"
echo "  i           - Show Bus Pirate info"
echo "  v           - Check voltages"
echo "  m           - Mode menu"
echo "  W           - Power supplies ON"
echo ""
echo "I2C Macros:"
echo "  (0)         - Macro menu"
echo "  (1)         - 7-bit address search"
echo "  (2)         - I2C sniffer"
echo ""
echo "Write Format:"
echo "  [device_addr high_byte low_byte data...]"
echo "  Example: [0xA0 0x00 0x69 0x42 0x42 0x42]"
echo ""
echo "Read Format:"
echo "  [device_addr r:n]  - Read n bytes"
echo "  Example: [0xA1 r:20]"
echo ""
echo "Common I2C Addresses:"
echo "  0xA0/0xA1 - 24C256 EEPROM"
echo "  0x20-0x27 - MCP23017 GPIO expander"
echo "  0x20-0x27 - PCF8575 GPIO expander"
echo ""
echo "Speed Settings:"
echo "  1 - ~5kHz"
echo "  2 - ~50kHz (recommended default)"
echo "  3 - ~100kHz"
echo "  4 - ~240kHz"
